class AvailabilitySlot {
  const AvailabilitySlot({
    required this.id,
    required this.departmentId,
    required this.departmentName,
    required this.doctorId,
    required this.doctorName,
    required this.startAt,
    required this.endAt,
    required this.status,
  });

  factory AvailabilitySlot.fromJson(Map<String, dynamic> json) {
    return AvailabilitySlot(
      id: json['id'] as String? ?? '',
      departmentId: json['department_id'] as String? ?? '',
      departmentName: json['department_name'] as String? ?? '',
      doctorId: json['doctor_id'] as String? ?? '',
      doctorName: json['doctor_name'] as String? ?? '',
      startAt: DateTime.parse(json['start_at'] as String).toLocal(),
      endAt: DateTime.parse(json['end_at'] as String).toLocal(),
      status: json['status'] as String? ?? 'available',
    );
  }

  final String id;
  final String departmentId;
  final String departmentName;
  final String doctorId;
  final String doctorName;
  final DateTime startAt;
  final DateTime endAt;
  final String status;

  bool get isBooked => status == 'booked';
  bool get isBlocked => status == 'blocked';
  bool get isPast => endAt.isBefore(DateTime.now());
  bool get isNearTerm {
    final now = DateTime.now();
    return startAt.difference(DateTime(now.year, now.month, now.day)).inDays <=
        1;
  }
}

class SlotDraft {
  const SlotDraft({
    required this.departmentId,
    required this.doctorId,
    required this.date,
    required this.startTime,
    required this.endTime,
    required this.status,
  });

  final String departmentId;
  final String doctorId;
  final DateTime date;
  final String startTime;
  final String endTime;
  final String status;

  Map<String, dynamic> toJson() {
    return {
      'department_id': departmentId,
      'doctor_id': doctorId,
      'date': _date(date),
      'start_time': '$startTime:00',
      'end_time': '$endTime:00',
      'status': status,
    };
  }
}

class TimeRangeDraft {
  const TimeRangeDraft({required this.startTime, required this.endTime});

  final String startTime;
  final String endTime;

  Map<String, dynamic> toJson() {
    return {'start_time': '$startTime:00', 'end_time': '$endTime:00'};
  }
}

class BulkSlotDraft {
  const BulkSlotDraft({
    required this.departmentId,
    required this.doctorId,
    required this.date,
    required this.status,
    required this.ranges,
  });

  final String departmentId;
  final String doctorId;
  final DateTime date;
  final String status;
  final List<TimeRangeDraft> ranges;

  Map<String, dynamic> toJson() {
    return {
      'department_id': departmentId,
      'doctor_id': doctorId,
      'date': _date(date),
      'status': status,
      'ranges': ranges.map((item) => item.toJson()).toList(),
    };
  }
}

class AutoGenerateDraft {
  const AutoGenerateDraft({
    required this.departmentId,
    required this.doctorId,
    required this.startDate,
    required this.endDate,
    required this.weekdays,
    required this.startTime,
    required this.endTime,
    required this.slotDurationMinutes,
    required this.status,
  });

  final String departmentId;
  final String doctorId;
  final DateTime startDate;
  final DateTime endDate;
  final List<int> weekdays;
  final String startTime;
  final String endTime;
  final int slotDurationMinutes;
  final String status;

  Map<String, dynamic> toJson() {
    return {
      'department_id': departmentId,
      'doctor_id': doctorId,
      'start_date': _date(startDate),
      'end_date': _date(endDate),
      'weekdays': weekdays,
      'start_time': '$startTime:00',
      'end_time': '$endTime:00',
      'slot_duration_minutes': slotDurationMinutes,
      'status': status,
    };
  }
}

class CleanupResult {
  const CleanupResult({
    required this.deleted,
    required this.matched,
    required this.checked,
  });

  factory CleanupResult.fromJson(Map<String, dynamic> json) {
    return CleanupResult(
      deleted: json['deleted'] as int? ?? 0,
      matched: json['matched'] as int? ?? 0,
      checked: json['checked'] as int? ?? 0,
    );
  }

  final int deleted;
  final int matched;
  final int checked;
}

String _date(DateTime value) {
  return '${value.year.toString().padLeft(4, '0')}-'
      '${value.month.toString().padLeft(2, '0')}-'
      '${value.day.toString().padLeft(2, '0')}';
}
