import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:http/http.dart' as http;

import '../../../core/app_config.dart';
import '../../../firebase/auth_providers.dart';
import '../../departments/domain/department.dart';
import '../../doctors/domain/doctor.dart';
import '../domain/availability_slot.dart';

const _slotMutationTimeout = Duration(seconds: 90);

final availabilitySlotRepositoryProvider = Provider<AvailabilitySlotRepository>(
  (ref) => AvailabilitySlotRepository(auth: ref.watch(firebaseAuthProvider)),
);

class AvailabilitySlotData {
  const AvailabilitySlotData({
    required this.departments,
    required this.doctors,
    required this.slots,
  });

  final List<Department> departments;
  final List<Doctor> doctors;
  final List<AvailabilitySlot> slots;
}

class SlotFilters {
  const SlotFilters({this.departmentId, this.doctorId, this.date});

  final String? departmentId;
  final String? doctorId;
  final DateTime? date;
}

class AvailabilitySlotRepository {
  AvailabilitySlotRepository({FirebaseAuth? auth, http.Client? client})
    : _auth = auth,
      _client = client ?? http.Client();

  final FirebaseAuth? _auth;
  final http.Client _client;

  static AvailabilitySlotData? _cachedData;

  AvailabilitySlotData? get cachedData => _cachedData;

  Future<AvailabilitySlotData> fetch(SlotFilters filters) async {
    final headers = await _authHeaders();
    try {
      final slotUri =
          Uri.parse('${AppConfig.backendBaseUrl}/availability-slots').replace(
            queryParameters: {
              if (filters.departmentId != null)
                'department_id': filters.departmentId!,
              if (filters.doctorId != null) 'doctor_id': filters.doctorId!,
              if (filters.date != null) 'selected_date': _date(filters.date!),
            },
          );
      final responses = await Future.wait([
        _client
            .get(slotUri, headers: headers)
            .timeout(const Duration(seconds: 12)),
        _client
            .get(
              Uri.parse('${AppConfig.backendBaseUrl}/departments'),
              headers: headers,
            )
            .timeout(const Duration(seconds: 12)),
        _client
            .get(
              Uri.parse('${AppConfig.backendBaseUrl}/doctors/admin'),
              headers: headers,
            )
            .timeout(const Duration(seconds: 12)),
      ]);
      if (responses.any((response) => response.statusCode != 200)) {
        final failed = responses.firstWhere(
          (response) => response.statusCode != 200,
        );
        throw AvailabilitySlotException(_backendMessage(failed.body));
      }
      _cachedData = AvailabilitySlotData(
        slots: (jsonDecode(responses[0].body) as List<dynamic>)
            .map(
              (item) => AvailabilitySlot.fromJson(item as Map<String, dynamic>),
            )
            .toList(),
        departments: (jsonDecode(responses[1].body) as List<dynamic>)
            .map((item) => Department.fromJson(item as Map<String, dynamic>))
            .toList(),
        doctors: (jsonDecode(responses[2].body) as List<dynamic>)
            .map((item) => Doctor.fromJson(item as Map<String, dynamic>))
            .toList(),
      );
      return _cachedData!;
    } on SocketException {
      throw const AvailabilitySlotException(
        'The backend is unreachable right now.',
      );
    } on TimeoutException {
      throw const AvailabilitySlotException(
        'The backend took too long to respond.',
      );
    }
  }

  Future<void> create(SlotDraft draft) async {
    await _send(
      'POST',
      '${AppConfig.backendBaseUrl}/availability-slots',
      draft.toJson(),
    );
  }

  Future<void> update(String slotId, SlotDraft draft) async {
    await _send(
      'PUT',
      '${AppConfig.backendBaseUrl}/availability-slots/${Uri.encodeComponent(slotId)}',
      draft.toJson(),
    );
  }

  Future<void> bulkCreate(BulkSlotDraft draft) async {
    await _send(
      'POST',
      '${AppConfig.backendBaseUrl}/availability-slots/bulk',
      draft.toJson(),
    );
  }

  Future<void> autoGenerate(AutoGenerateDraft draft) async {
    await _send(
      'POST',
      '${AppConfig.backendBaseUrl}/availability-slots/auto-generate',
      draft.toJson(),
    );
  }

  Future<void> updateStatus(String slotId, String status) async {
    await _send(
      'PATCH',
      '${AppConfig.backendBaseUrl}/availability-slots/${Uri.encodeComponent(slotId)}/status',
      {'status': status},
    );
  }

  Future<CleanupResult> cleanup(SlotFilters filters) async {
    final uri =
        Uri.parse(
          '${AppConfig.backendBaseUrl}/availability-slots/cleanup',
        ).replace(
          queryParameters: {
            if (filters.departmentId != null)
              'department_id': filters.departmentId!,
            if (filters.doctorId != null) 'doctor_id': filters.doctorId!,
          },
        );
    final response = await _client
        .post(uri, headers: await _authHeaders())
        .timeout(_slotMutationTimeout);
    if (response.statusCode == 200) {
      return CleanupResult.fromJson(
        jsonDecode(response.body) as Map<String, dynamic>,
      );
    }
    throw AvailabilitySlotException(_backendMessage(response.body));
  }

  Future<void> _send(
    String method,
    String url,
    Map<String, dynamic> body,
  ) async {
    try {
      final headers = await _authHeaders();
      final uri = Uri.parse(url);
      final encoded = jsonEncode(body);
      final response = switch (method) {
        'POST' =>
          await _client
              .post(uri, headers: headers, body: encoded)
              .timeout(_slotMutationTimeout),
        'PUT' =>
          await _client
              .put(uri, headers: headers, body: encoded)
              .timeout(_slotMutationTimeout),
        'PATCH' =>
          await _client
              .patch(uri, headers: headers, body: encoded)
              .timeout(_slotMutationTimeout),
        _ => throw const AvailabilitySlotException(
          'Unsupported slot operation.',
        ),
      };
      if (response.statusCode < 200 || response.statusCode >= 300) {
        throw AvailabilitySlotException(_backendMessage(response.body));
      }
    } on SocketException {
      throw const AvailabilitySlotException(
        'The backend is unreachable right now.',
      );
    } on TimeoutException {
      throw const AvailabilitySlotException(
        'The backend took too long to respond.',
      );
    }
  }

  Future<Map<String, String>> _authHeaders() async {
    final token = await _auth?.currentUser?.getIdToken(true);
    if (token == null) {
      throw const AvailabilitySlotException(
        'Please sign in again before continuing.',
      );
    }
    return {
      HttpHeaders.authorizationHeader: 'Bearer $token',
      HttpHeaders.contentTypeHeader: 'application/json',
    };
  }

  String _backendMessage(String body) {
    try {
      final json = jsonDecode(body) as Map<String, dynamic>;
      final detail = json['detail'];
      if (detail is String && detail.isNotEmpty) return detail;
    } catch (_) {
      // Friendly fallback below.
    }
    return 'We could not load availability slots right now.';
  }
}

class AvailabilitySlotException implements Exception {
  const AvailabilitySlotException(this.message);

  final String message;

  @override
  String toString() => message;
}

String _date(DateTime value) {
  return '${value.year.toString().padLeft(4, '0')}-'
      '${value.month.toString().padLeft(2, '0')}-'
      '${value.day.toString().padLeft(2, '0')}';
}
